// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {
    host: 'http://www.thinkero.us',
    defaultPort: 10300,
    memcached: {
      enabled: true,
      defaultHost: 'seo-memcache-production',
      defaultPort: 11211,
      maxValue: 2097152,
      connectRetries: 0,
      key: 'thinkero.us'
    },
    logentries: {
      enabled: false,
      token: 'YOUR_LOGENTRIES_TOKEN_HERE'
    },
    getParamWhitelist: ['page']
  };

  module.exports = config;

}).call(this);
